name: My first workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Print first job
        run: echo "First Job"

      - name: list files
        run: ls
        
      - name: Read file
        run: cat  README.md